### ISSUE TITLE
Does it support OpenGraph Tags

### ISSUE THREAD

**Issue by alladas** [iJackUA/yii2-sharelinks-widget#5]
Hi @iJackUA,
I found your plugin very useful, but as in the title,  I wonder if it supports og:tags if present in the page header.
If not, may you provide me with any tips/hints on how to make it work with them?
In advance thanks.

**Comment by iJackUA** [comment]
Thank you.
This plugin by itself does nothing with og:tags. It just opens "share" page on different soc. networks - and each social network handles og:tags by it's own way.
So as a general rule - it does not matter how did you post a link to your site "with this plugin" or "directly to social net", og:tags fro site page will be handled by social net.

**Comment by alladas** [comment]
Many thanks for your reactivity and for the info.
Easy and handy. In addition tiny :+1:
