### ISSUE TITLE
Interest in continue the project

### ISSUE THREAD

**Issue by glpzzz** [iJackUA/yii2-sharelinks-widget#8]
Hi! we have been using this extension for several years. Today we decided to forked it on https://github.com/daxslab/yii2-sharelinks-widget because you have marked your original project as abandoned on Packagist. If you like you can suggest this one as a replacement. Best regards and thanks for the extension.

**Comment by iJackUA** [comment]
Sure, thank you for the fork, have added your package as a suggestion.

**Comment by glpzzz** [comment]
Thanks to you!
